TICKET_TYPES = {
    "onboarding": "Colleague Onboarding",
    "offboarding": "Colleague Offboarding",
    "incident": "Incident",
    "hardware_request": "Hardware Request",
    "access_google": "Google Workspace Request",
    "access_commando": "Commando Access Request",
    "access_nucleus": "Nucleus Access Request",
    "access_superset": "SuperSet Access Request",
    "access_platform": "Platform Scopes Add/Remove",
    "access_lending": "Lending Portal",
    "access_aws": "AWS Access",
    "access_platform_role": "Create New Platform Role",
    "system_problem": "Report a System Problem",
    "it_service_request": "IT Service Request",
}

TICKET_FORM_FIELDS = {
    "onboarding": [
        {"key": "full_name", "label": "Full Name", "type": "text", "required": True},
        {"key": "date_of_joining", "label": "Date of Joining", "type": "date", "required": True},
        {"key": "employment_type", "label": "Employment Type", "type": "select",
         "options": ["Permanent", "Contractual", "Intern"], "required": True},
        {"key": "previous_employment", "label": "Previous Employment", "type": "text", "required": False},
        {"key": "work_experience", "label": "Work Experience", "type": "text", "required": False},
        {"key": "personal_email", "label": "Personal Email ID", "type": "email", "required": False},
        {"key": "preferred_email", "label": "Preferred Email ID", "type": "email", "required": True},
        {"key": "line_manager", "label": "Line Manager", "type": "text", "required": True},
        {"key": "cnic", "label": "CNIC Number", "type": "text", "required": False},
        {"key": "mobile_number", "label": "Contact Number", "type": "text", "required": False},
        {"key": "job_title", "label": "Job Title", "type": "text", "required": True},
        {"key": "department", "label": "Department", "type": "text", "required": True},
        {"key": "relocation_required", "label": "Relocation Required", "type": "select",
         "options": ["Yes", "No"], "required": False},
        {"key": "city", "label": "City", "type": "text", "required": False},
        {"key": "it_essentials", "label": "IT Essentials", "type": "multiselect",
         "options": ["Laptop", "Gmail ID", "Mobile Device", "VPN Access", "ID Card"], "required": False},
        {"key": "reason_for_hire", "label": "Reason for Hire", "type": "select",
         "options": ["New Position", "Replacement", "Expansion"], "required": False},
        {"key": "comments", "label": "Comments", "type": "textarea", "required": False},
    ],
    "offboarding": [
        {"key": "employee_name", "label": "Employee Name", "type": "text", "required": True},
        {"key": "employee_email", "label": "Employee Email", "type": "email", "required": True},
        {"key": "last_working_date", "label": "Last Working Date", "type": "date", "required": True},
        {"key": "department", "label": "Department", "type": "text", "required": True},
        {"key": "line_manager", "label": "Line Manager", "type": "text", "required": True},
        {"key": "reason_for_leaving", "label": "Reason for Leaving", "type": "select",
         "options": ["Resignation", "Contract End", "Termination", "Retirement"], "required": True},
        {"key": "assets_to_return", "label": "Assets to Return", "type": "multiselect",
         "options": ["Laptop", "Mobile Device", "ID Card", "Access Card", "Keys"], "required": False},
        {"key": "comments", "label": "Comments", "type": "textarea", "required": False},
    ],
    "access_google": [
        {"key": "requested_for", "label": "Requested For (Name/Email)", "type": "text", "required": True},
        {"key": "request_type", "label": "Request Type", "type": "select",
         "options": ["Create New Account", "Delete Account", "Password Reset", "Access Modification", "Group Addition"], "required": True},
        {"key": "mobile_number", "label": "Mobile Number", "type": "text", "required": False},
        {"key": "justification", "label": "Justification (Requirement)", "type": "textarea", "required": True},
    ],
    "access_commando": [
        {"key": "requested_for", "label": "Requested For (Name/Email)", "type": "text", "required": True},
        {"key": "access_type", "label": "Access Type", "type": "select",
         "options": ["Read Only", "Read/Write", "Admin", "Remove Access"], "required": True},
        {"key": "mobile_number", "label": "Mobile Number", "type": "text", "required": False},
        {"key": "justification", "label": "Justification (Requirement)", "type": "textarea", "required": True},
    ],
    "access_nucleus": [
        {"key": "requested_for", "label": "Requested For (Name/Email)", "type": "text", "required": True},
        {"key": "nucleus_module", "label": "Nucleus Module", "type": "select",
         "options": [
            "Fleet Manager", "Fleet Supervisor", "Fleet Executive",
            "Agent Team Lead", "Cash Tower Cash Officer", "Cash Tower Cash Supervisor",
            "LiveOps Care", "LiveOps Executive", "Nucleus Liveops Executive",
            "CATALOG_MASTER", "CATALOG_VIEWER", "CATALOG_OPS", "CATALOG_FINANCE",
            "CATALOG_COMMERCIAL", "CATALOG_COMMERCIAL_SUPERVISOR",
            "Catalog All Access", "Catalog View And Create Product",
            "Catalog Pricing", "Catalog Pricing Supervisor", "Catalog Pricing Viewer",
            "Catalog Other Details",
            "General Order Creator", "Order Manager", "Order All Access",
            "Discount Order Creator", "Order Discount Editor", "Discount Approval Manager",
            "Chief Justice - Order", "Nucleus Order View",
            "Order (Category Manager - Industrial)", "Order (Finance - Industrial)",
            "Order (Commercial - Industrial)", "Order (Operations - Industrial)",
            "Vendor View", "Vendor Create", "Vendor Management (FINANCE)",
            "Contract Create", "Bundle Create",
            "Promo Manager", "Promo View", "Promo Create", "CAMPAIGN_MASTER",
            "Customer Module - View", "Customer Module - Update", "Customer All Access",
            "INVOICE_FINANCE", "INVOICE_RESOLVER", "INVOICE_CONTROLLER",
            "PO COMMERCIALS", "PO_COMMERCIALS_SUPERVISOR", "PO FINANCE", "PO_FINANCE_SUPERVISOR",
            "Commercials Manager", "Commercials Brand Manager",
            "WMS Super User", "WMS COMMERCIALS", "WMS OPS", "WMS OPS Supervisor",
            "WMS Finance", "WMS Packer",
            "Cycle Count View Only", "Cycle Count Initiation", "Cycle Count Master Role",
            "Route Viewer", "Route Planner",
            "Route Viewer - Routing Executive", "Route Planner - Routing Supervisor",
            "Lending Collection Core", "Lending Army Chief", "Lending Biz Core",
            "BR Executive", "BA Executive",
            "IRD Executive", "IRM",
            "Dropship Fulfilment - Ops", "OLP Packer",
            "Sales Return", "Sales Return Approver",
            "Ghalib Admin", "Prime Admin", "PRIME_KPO",
            "Partner Manager", "BD Industrial",
            "Demand Quotation", "Retail - Customer Update",
         ], "required": True},
        {"key": "mobile_number", "label": "Mobile Number", "type": "text", "required": True},
        {"key": "justification", "label": "Justification (Requirement)", "type": "textarea", "required": True},
    ],
    "access_superset": [
        {"key": "requested_for", "label": "Requested For (Name/Email)", "type": "text", "required": True},
        {"key": "access_type", "label": "Access Type", "type": "select",
         "options": ["Viewer", "Alpha", "SQL Lab", "Admin"], "required": True},
        {"key": "mobile_number", "label": "Mobile Number", "type": "text", "required": False},
        {"key": "justification", "label": "Justification (Requirement)", "type": "textarea", "required": True},
    ],
    "access_platform": [
        {"key": "requested_for", "label": "Requested For (Name/Email)", "type": "text", "required": True},
        {"key": "scope_action", "label": "Action", "type": "select",
         "options": ["Add", "Remove"], "required": True},
        {"key": "scope_name", "label": "Scope / Permission Name", "type": "text", "required": True},
        {"key": "platform", "label": "Platform", "type": "text", "required": True},
        {"key": "mobile_number", "label": "Mobile Number", "type": "text", "required": False},
        {"key": "justification", "label": "Justification (Requirement)", "type": "textarea", "required": True},
    ],
    "access_lending": [
        {"key": "lending_module", "label": "Lending Portal Module", "type": "multiselect",
         "options": ["Lending Collection Core", "Loan Origination", "Credit Assessment", "Repayment Management"], "required": True},
        {"key": "mobile_number", "label": "Mobile Number", "type": "text", "required": True},
        {"key": "justification", "label": "Justification (Requirement)", "type": "textarea", "required": True},
    ],
    "system_problem": [
        {"key": "affected_system", "label": "Affected System / Application", "type": "text", "required": True},
        {"key": "problem_description", "label": "Problem Description", "type": "textarea", "required": True},
        {"key": "steps_to_reproduce", "label": "Steps to Reproduce", "type": "textarea", "required": False},
        {"key": "impact_level", "label": "Impact Level", "type": "select",
         "options": ["Low", "Medium", "High", "Critical"], "required": True},
    ],
    "incident": [
        {"key": "summary", "label": "Summary", "type": "text", "required": True},
        {"key": "affected_system", "label": "Affected System / Service", "type": "text", "required": True},
        {"key": "incident_description", "label": "Incident Description", "type": "textarea", "required": True},
        {"key": "impact_level", "label": "Impact Level", "type": "select",
         "options": ["Low", "Medium", "High", "Critical"], "required": True},
        {"key": "steps_to_reproduce", "label": "Steps to Reproduce", "type": "textarea", "required": False},
        {"key": "workaround", "label": "Workaround Available", "type": "select",
         "options": ["Yes", "No"], "required": False},
        {"key": "comments", "label": "Comments", "type": "textarea", "required": False},
    ],
    "hardware_request": [
        {"key": "requested_for", "label": "Requested For (Name/Email)", "type": "text", "required": True},
        {"key": "hardware_type", "label": "Hardware Type", "type": "select",
         "options": ["Laptop", "Desktop", "Monitor", "Keyboard/Mouse", "Mobile Device", "Headset", "Other"], "required": True},
        {"key": "justification", "label": "Justification / Business Need", "type": "textarea", "required": True},
        {"key": "urgency", "label": "Urgency", "type": "select",
         "options": ["Low", "Medium", "High"], "required": False},
        {"key": "comments", "label": "Comments", "type": "textarea", "required": False},
    ],
    "it_service_request": [
        {"key": "requested_for", "label": "Requested For (Name/Email)", "type": "text", "required": True},
        {"key": "request_type", "label": "Request Type", "type": "select",
         "options": ["New Setup", "Configuration Change", "Software Install", "Other"], "required": True},
        {"key": "description", "label": "Description", "type": "textarea", "required": True},
        {"key": "comments", "label": "Comments", "type": "textarea", "required": False},
    ],
    "access_aws": [
        {"key": "requested_for", "label": "Requested For (Name/Email)", "type": "text", "required": True},
        {"key": "aws_account", "label": "AWS Account / Environment", "type": "select",
         "options": ["Production", "Staging", "Development", "UAT"], "required": True},
        {"key": "access_level", "label": "Access Level", "type": "select",
         "options": ["Read Only", "Power User", "Admin", "Custom Policy"], "required": True},
        {"key": "services", "label": "AWS Services Required", "type": "text", "required": False},
        {"key": "mobile_number", "label": "Mobile Number", "type": "text", "required": False},
        {"key": "justification", "label": "Justification (Requirement)", "type": "textarea", "required": True},
    ],
    "access_platform_role": [
        {"key": "requested_for", "label": "Requested For (Name/Email)", "type": "text", "required": True},
        {"key": "role_name", "label": "Role Name", "type": "text", "required": True},
        {"key": "platform", "label": "Platform / System", "type": "text", "required": True},
        {"key": "permissions", "label": "Permissions to Include", "type": "textarea", "required": True},
        {"key": "mobile_number", "label": "Mobile Number", "type": "text", "required": False},
        {"key": "justification", "label": "Justification (Requirement)", "type": "textarea", "required": True},
    ],
}

WORKFLOW_DEFINITIONS = {
    "onboarding": {
        "name": "IT Onboarding Workflow",
        "states": [
            {"name": "WAITING FOR SUPPORT",  "color": "#dbeafe", "text_color": "#1e40af", "is_initial": True,  "is_terminal": False, "order": 0},
            {"name": "ACKNOWLEDGE",          "color": "#bfdbfe", "text_color": "#1d4ed8", "is_initial": False, "is_terminal": False, "order": 1},
            {"name": "IN PROGRESS",          "color": "#3b82f6", "text_color": "#ffffff", "is_initial": False, "is_terminal": False, "order": 2},
            {"name": "HOLD",                 "color": "#fed7aa", "text_color": "#9a3412", "is_initial": False, "is_terminal": False, "order": 3},
            {"name": "CREATE CREDENTIALS",   "color": "#e0e7ff", "text_color": "#4338ca", "is_initial": False, "is_terminal": False, "order": 4},
            {"name": "CANCELED",             "color": "#fecaca", "text_color": "#7f1d1d", "is_initial": False, "is_terminal": True,  "order": 5},
            {"name": "RESOLVED",             "color": "#bbf7d0", "text_color": "#14532d", "is_initial": False, "is_terminal": True,  "order": 6},
        ],
        "transitions": [
            {"from_state": "WAITING FOR SUPPORT", "to_state": "ACKNOWLEDGE",       "label": "Acknowledged"},
            {"from_state": "ACKNOWLEDGE",          "to_state": "IN PROGRESS",       "label": "In Progress"},
            {"from_state": "IN PROGRESS",          "to_state": "HOLD",              "label": "Hold"},
            {"from_state": "HOLD",                 "to_state": "IN PROGRESS",       "label": "Back in Progress"},
            {"from_state": "IN PROGRESS",          "to_state": "CREATE CREDENTIALS","label": "Create Credentials"},
            {"from_state": "CREATE CREDENTIALS",   "to_state": "IN PROGRESS",       "label": "Back in Progress"},
            {"from_state": "IN PROGRESS",          "to_state": "RESOLVED",          "label": "Resolved"},
            {"from_state": "IN PROGRESS",          "to_state": "CANCELED",          "label": "Canceled"},
        ],
    },
    "offboarding": {
        "name": "IT Offboarding Workflow",
        "states": [
            {"name": "WAITING FOR SUPPORT", "color": "#dbeafe", "text_color": "#1e40af", "is_initial": True,  "is_terminal": False, "order": 0},
            {"name": "ACKNOWLEDGE",         "color": "#bfdbfe", "text_color": "#1d4ed8", "is_initial": False, "is_terminal": False, "order": 1},
            {"name": "IN PROGRESS",         "color": "#3b82f6", "text_color": "#ffffff", "is_initial": False, "is_terminal": False, "order": 2},
            {"name": "HOLD",                "color": "#fed7aa", "text_color": "#9a3412", "is_initial": False, "is_terminal": False, "order": 3},
            {"name": "CLOSE CREDENTIALS",   "color": "#e0e7ff", "text_color": "#4338ca", "is_initial": False, "is_terminal": False, "order": 4},
            {"name": "WAITING FOR LAPTOP",  "color": "#dbeafe", "text_color": "#1e40af", "is_initial": False, "is_terminal": False, "order": 5},
            {"name": "CANCELED",            "color": "#fecaca", "text_color": "#7f1d1d", "is_initial": False, "is_terminal": True,  "order": 6},
            {"name": "RESOLVED",            "color": "#bbf7d0", "text_color": "#14532d", "is_initial": False, "is_terminal": True,  "order": 7},
        ],
        "transitions": [
            {"from_state": "WAITING FOR SUPPORT", "to_state": "ACKNOWLEDGE",       "label": "Acknowledged"},
            {"from_state": "ACKNOWLEDGE",         "to_state": "IN PROGRESS",       "label": "In Progress"},
            {"from_state": "IN PROGRESS",         "to_state": "HOLD",              "label": "Hold"},
            {"from_state": "HOLD",                "to_state": "IN PROGRESS",       "label": "Back in Progress"},
            {"from_state": "IN PROGRESS",         "to_state": "CLOSE CREDENTIALS", "label": "Deactivate User"},
            {"from_state": "HOLD",                "to_state": "CLOSE CREDENTIALS", "label": "Deactivate User"},
            {"from_state": "CLOSE CREDENTIALS",   "to_state": "WAITING FOR LAPTOP","label": "Waiting for the Laptop"},
            {"from_state": "IN PROGRESS",         "to_state": "RESOLVED",          "label": "Resolved"},
            {"from_state": "WAITING FOR LAPTOP",  "to_state": "RESOLVED",          "label": "Resolved"},
            {"from_state": "IN PROGRESS",         "to_state": "CANCELED",          "label": "Canceled"},
        ],
    },
    "incident": {
        "name": "IT: Incident Management Workflow",
        "states": [
            {"name": "OPEN",             "color": "#dbeafe", "text_color": "#1e40af", "is_initial": True,  "is_terminal": False, "order": 0},
            {"name": "WORK IN PROGRESS", "color": "#3b82f6", "text_color": "#ffffff", "is_initial": False, "is_terminal": False, "order": 1},
            {"name": "PENDING",          "color": "#fed7aa", "text_color": "#9a3412", "is_initial": False, "is_terminal": False, "order": 2},
            {"name": "COMPLETED",        "color": "#bbf7d0", "text_color": "#14532d", "is_initial": False, "is_terminal": True,  "order": 3},
            {"name": "CANCELED",         "color": "#fecaca", "text_color": "#7f1d1d", "is_initial": False, "is_terminal": True,  "order": 4},
            {"name": "CLOSED",           "color": "#f1f5f9", "text_color": "#475569", "is_initial": False, "is_terminal": True,  "order": 5},
        ],
        "transitions": [
            {"from_state": "OPEN",             "to_state": "WORK IN PROGRESS", "label": "Investigate"},
            {"from_state": "OPEN",             "to_state": "PENDING",          "label": "Pending"},
            {"from_state": "OPEN",             "to_state": "COMPLETED",        "label": "Resolve"},
            {"from_state": "OPEN",             "to_state": "CANCELED",         "label": "Cancel"},
            {"from_state": "WORK IN PROGRESS", "to_state": "PENDING",          "label": "Pending"},
            {"from_state": "WORK IN PROGRESS", "to_state": "COMPLETED",        "label": "Resolve"},
            {"from_state": "WORK IN PROGRESS", "to_state": "CANCELED",         "label": "Cancel"},
            {"from_state": "PENDING",          "to_state": "WORK IN PROGRESS", "label": "Back to Work in Progress"},
            {"from_state": "PENDING",          "to_state": "CANCELED",         "label": "Cancel"},
            {"from_state": "COMPLETED",        "to_state": "CLOSED",           "label": "Close"},
            {"from_state": "CANCELED",         "to_state": "CLOSED",           "label": "Close"},
        ],
    },
    "hardware_request": {
        "name": "IT: Hardware Request Workflow",
        "states": [
            {"name": "WAITING FOR SUPPORT", "color": "#dbeafe", "text_color": "#1e40af", "is_initial": True,  "is_terminal": False, "order": 0},
            {"name": "ACKNOWLEDGE",         "color": "#bfdbfe", "text_color": "#1d4ed8", "is_initial": False, "is_terminal": False, "order": 1},
            {"name": "IN PROGRESS",         "color": "#3b82f6", "text_color": "#ffffff", "is_initial": False, "is_terminal": False, "order": 2},
            {"name": "HOLD",                "color": "#fed7aa", "text_color": "#9a3412", "is_initial": False, "is_terminal": False, "order": 3},
            {"name": "PENDING VENDOR",      "color": "#e0e7ff", "text_color": "#4338ca", "is_initial": False, "is_terminal": False, "order": 4},
            {"name": "CANCELED",            "color": "#fecaca", "text_color": "#7f1d1d", "is_initial": False, "is_terminal": True,  "order": 5},
            {"name": "RESOLVED",            "color": "#bbf7d0", "text_color": "#14532d", "is_initial": False, "is_terminal": True,  "order": 6},
        ],
        "transitions": [
            {"from_state": "WAITING FOR SUPPORT", "to_state": "ACKNOWLEDGE",    "label": "Acknowledged"},
            {"from_state": "ACKNOWLEDGE",          "to_state": "IN PROGRESS",   "label": "In Progress"},
            {"from_state": "IN PROGRESS",          "to_state": "HOLD",          "label": "Hold"},
            {"from_state": "IN PROGRESS",          "to_state": "PENDING VENDOR","label": "Pending Vendor"},
            {"from_state": "IN PROGRESS",          "to_state": "RESOLVED",      "label": "Resolved"},
            {"from_state": "IN PROGRESS",          "to_state": "CANCELED",      "label": "Canceled"},
            {"from_state": "HOLD",                 "to_state": "IN PROGRESS",   "label": "Back in Progress"},
            {"from_state": "PENDING VENDOR",       "to_state": "IN PROGRESS",   "label": "Back in Progress"},
        ],
    },
    "service_request_approval": {
        "name": "IT: Service Request with Approval Workflow",
        "states": [
            {"name": "AWAITING APPROVAL",   "color": "#fef9c3", "text_color": "#854d0e", "is_initial": True,  "is_terminal": False, "order": 0},
            {"name": "WAITING FOR SUPPORT", "color": "#dbeafe", "text_color": "#1e40af", "is_initial": False, "is_terminal": False, "order": 1},
            {"name": "ACKNOWLEDGE",         "color": "#bfdbfe", "text_color": "#1d4ed8", "is_initial": False, "is_terminal": False, "order": 2},
            {"name": "IN PROGRESS",         "color": "#3b82f6", "text_color": "#ffffff", "is_initial": False, "is_terminal": False, "order": 3},
            {"name": "HOLD",                "color": "#fed7aa", "text_color": "#9a3412", "is_initial": False, "is_terminal": False, "order": 4},
            {"name": "REJECTED",            "color": "#fecaca", "text_color": "#7f1d1d", "is_initial": False, "is_terminal": True,  "order": 5},
            {"name": "RESOLVED",            "color": "#bbf7d0", "text_color": "#14532d", "is_initial": False, "is_terminal": True,  "order": 6},
        ],
        "transitions": [
            {"from_state": "AWAITING APPROVAL",   "to_state": "WAITING FOR SUPPORT", "label": "Waiting for support"},
            {"from_state": "AWAITING APPROVAL",   "to_state": "REJECTED",            "label": "Not Approved"},
            {"from_state": "WAITING FOR SUPPORT", "to_state": "ACKNOWLEDGE",         "label": "Acknowledge"},
            {"from_state": "WAITING FOR SUPPORT", "to_state": "IN PROGRESS",         "label": "In Progress"},
            {"from_state": "WAITING FOR SUPPORT", "to_state": "RESOLVED",            "label": "Auto Resolved"},
            {"from_state": "ACKNOWLEDGE",         "to_state": "IN PROGRESS",         "label": "In Progress"},
            {"from_state": "IN PROGRESS",         "to_state": "HOLD",                "label": "Hold"},
            {"from_state": "HOLD",                "to_state": "IN PROGRESS",         "label": "In Progress"},
        ],
    },
    "it_service_request": {
        "name": "IT: Service Request For IT Workflow",
        "states": [
            {"name": "WAITING FOR SUPPORT", "color": "#dbeafe", "text_color": "#1e40af", "is_initial": True,  "is_terminal": False, "order": 0},
            {"name": "ACKNOWLEDGE",         "color": "#bfdbfe", "text_color": "#1d4ed8", "is_initial": False, "is_terminal": False, "order": 1},
            {"name": "IN PROGRESS",         "color": "#3b82f6", "text_color": "#ffffff", "is_initial": False, "is_terminal": False, "order": 2},
            {"name": "HOLD",                "color": "#fed7aa", "text_color": "#9a3412", "is_initial": False, "is_terminal": False, "order": 3},
            {"name": "RESOLVED",            "color": "#bbf7d0", "text_color": "#14532d", "is_initial": False, "is_terminal": True,  "order": 4},
        ],
        "transitions": [
            {"from_state": "WAITING FOR SUPPORT", "to_state": "ACKNOWLEDGE", "label": "Acknowledged"},
            {"from_state": "ACKNOWLEDGE",          "to_state": "IN PROGRESS", "label": "In Progress"},
            {"from_state": "IN PROGRESS",          "to_state": "HOLD",        "label": "Hold"},
            {"from_state": "IN PROGRESS",          "to_state": "RESOLVED",    "label": "Resolved"},
            {"from_state": "WAITING FOR SUPPORT",  "to_state": "RESOLVED",    "label": "Resolved"},
            {"from_state": "HOLD",                 "to_state": "IN PROGRESS", "label": "Back in Progress"},
        ],
    },
    "default": {
        "name": "Standard Request Workflow",
        "states": [
            {"name": "AWAITING APPROVAL", "color": "#f1f5f9", "text_color": "#475569", "is_initial": True, "is_terminal": False, "order": 0},
            {"name": "WAITING FOR SUPPORT", "color": "#dbeafe", "text_color": "#1e40af", "is_initial": False, "is_terminal": False, "order": 1},
            {"name": "IN PROGRESS", "color": "#3b82f6", "text_color": "#ffffff", "is_initial": False, "is_terminal": False, "order": 2},
            {"name": "ACKNOWLEDGE", "color": "#bfdbfe", "text_color": "#1d4ed8", "is_initial": False, "is_terminal": False, "order": 3},
            {"name": "HOLD", "color": "#fed7aa", "text_color": "#9a3412", "is_initial": False, "is_terminal": False, "order": 4},
            {"name": "OPEN", "color": "#e0f2fe", "text_color": "#0369a1", "is_initial": False, "is_terminal": False, "order": 5},
            {"name": "RESOLVED", "color": "#bbf7d0", "text_color": "#14532d", "is_initial": False, "is_terminal": True, "order": 6},
            {"name": "REJECTED", "color": "#fecaca", "text_color": "#7f1d1d", "is_initial": False, "is_terminal": True, "order": 7},
        ],
        "transitions": [
            {"from_state": "AWAITING APPROVAL", "to_state": "WAITING FOR SUPPORT"},
            {"from_state": "AWAITING APPROVAL", "to_state": "REJECTED"},
            {"from_state": "WAITING FOR SUPPORT", "to_state": "IN PROGRESS"},
            {"from_state": "WAITING FOR SUPPORT", "to_state": "RESOLVED"},
            {"from_state": "IN PROGRESS", "to_state": "HOLD"},
            {"from_state": "IN PROGRESS", "to_state": "ACKNOWLEDGE"},
            {"from_state": "IN PROGRESS", "to_state": "RESOLVED"},
            {"from_state": "IN PROGRESS", "to_state": "WAITING FOR SUPPORT"},
            {"from_state": "ACKNOWLEDGE", "to_state": "IN PROGRESS"},
            {"from_state": "HOLD", "to_state": "IN PROGRESS"},
        ],
    },
}


def get_workflow_key(ticket_type: str) -> str:
    mapping = {
        "onboarding": "onboarding",
        "offboarding": "offboarding",
        "incident": "incident",
        "hardware_request": "hardware_request",
        "it_service_request": "it_service_request",
        "access_commando": "service_request_approval",
        "access_lending": "service_request_approval",
        "access_nucleus": "service_request_approval",
        "access_superset": "service_request_approval",
        "access_aws": "service_request_approval",
        "access_platform_role": "service_request_approval",
    }
    return mapping.get(ticket_type, "default")


def get_initial_status(ticket_type: str) -> str:
    wf_key = get_workflow_key(ticket_type)
    for state in WORKFLOW_DEFINITIONS[wf_key]["states"]:
        if state["is_initial"]:
            return state["name"]
    return "WAITING FOR SUPPORT"
